/* 
Bacon ipsum dolor amet jerky cupim venison, jowl strip steak burgdoggen tenderloin pork chop chicken tongue shank swine fatback kielbasa sausage. Turkey flank spare ribs, leberkas picanha tri-tip meatloaf cow pancetta hamburger pork chop. Short loin kevin ham, porchetta shankle venison andouille chuck t-bone corned beef chislic. Cupim pork chop fatback venison drumstick sirloin capicola ham ribeye pork. Shoulder turducken short ribs frankfurter. Ribeye cow filet mignon pork belly tail, pancetta chislic.

Biltong burgdoggen short loin tenderloin rump salami, pig sausage jowl brisket. Chicken cupim short ribs strip steak brisket tri-tip porchetta. Burgdoggen picanha ground round, short ribs shank bresaola spare ribs t-bone beef ribs pig chuck. Jerky beef sirloin, tri-tip turkey sausage porchetta ball tip picanha pork belly kevin shank tail. Jerky pig chislic frankfurter shank drumstick. Alcatra ribeye chuck leberkas frankfurter. Shankle cupim pork, flank fatback hamburger tenderloin pancetta picanha meatball kevin sirloin chislic.

Frankfurter kevin shankle pig, jowl chislic picanha landjaeger beef leberkas ham bacon tri-tip tenderloin ball tip. Frankfurter kevin ham hock capicola ground round pork loin prosciutto. Buffalo bacon ball tip pork chop, fatback pancetta cupim ribeye jowl. Swine porchetta burgdoggen, ham tail brisket pastrami ham hock beef t-bone landjaeger pancetta. Tenderloin filet mignon landjaeger, cow spare ribs pork chop shank turkey tri-tip porchetta venison chislic. Chislic short ribs alcatra pig picanha ribeye pork belly tongue fatback burgdoggen.

Chicken ball tip alcatra, turkey frankfurter capicola beef jowl flank. Bacon short ribs alcatra beef ribs pork loin corned beef tongue biltong landjaeger boudin short loin sausage pig brisket. Alcatra capicola biltong jerky shankle cupim chicken. Cow rump brisket kielbasa capicola tongue chuck, beef ham spare ribs biltong shank pastrami.

Alcatra kevin filet mignon shankle bresaola prosciutto cupim strip steak salami meatloaf bacon short loin. Chicken short ribs burgdoggen porchetta pork loin cupim strip steak sausage frankfurter brisket filet mignon ribeye. Jerky beef tri-tip pig cow ham shoulder pork chop tongue picanha ground round doner corned beef. Burgdoggen ball tip swine, pig brisket pork belly biltong drumstick. Swine chuck cow, capicola pancetta turducken tenderloin flank corned beef ham hock meatball hamburger sirloin turkey ribeye.

Beef boudin leberkas, bacon hamburger chuck pig tongue. Buffalo beef ribs hamburger t-bone chuck pork spare ribs biltong boudin. Pork chop doner short ribs, swine shank landjaeger ribeye flank. Porchetta venison flank ham hock shankle frankfurter. T-bone ham hock meatball, cow drumstick frankfurter sirloin.

Flank boudin capicola turkey kevin ribeye chislic picanha t-bone shankle cow. Chicken t-bone capicola flank cupim. Cupim biltong pork loin, pork belly turkey tail shoulder kielbasa tenderloin bacon ball tip short ribs. Kielbasa porchetta short ribs, fatback chuck pork loin leberkas ham hock turducken tenderloin sausage flank kevin pig shankle. Pork jerky sausage, shank salami kevin short loin beef ribs sirloin. Filet mignon burgdoggen biltong, ball tip short loin pork belly boudin salami prosciutto landjaeger jerky venison shank swine.

Leberkas picanha corned beef, doner chicken pork chop capicola boudin frankfurter ham hock buffalo. Shoulder ham hock pork loin swine bacon, short loin drumstick kevin burgdoggen cupim shank leberkas brisket porchetta spare ribs. T-bone doner bresaola, biltong pork sirloin pork loin meatloaf. Rump capicola jerky, shankle bresaola beef ribs turducken buffalo kevin porchetta tongue boudin meatloaf. Bacon shank short loin tongue pork chop ribeye. Kevin turducken leberkas, ground round beef frankfurter tri-tip ribeye tenderloin landjaeger pork belly ball tip corned beef jerky.

Corned beef pork chop bresaola, spare ribs pork loin leberkas brisket buffalo biltong beef. Venison shoulder strip steak, chuck pork frankfurter prosciutto leberkas. Cupim sausage shankle andouille, sirloin doner tri-tip short loin capicola t-bone ribeye pancetta venison ground round. Cow beef swine landjaeger tenderloin meatball jowl burgdoggen t-bone. Buffalo porchetta short loin jowl turkey chicken sirloin spare ribs. Venison andouille doner, pancetta pork chop porchetta bacon shankle swine turducken beef pork belly flank rump meatball.

Chicken pork tenderloin pork loin sausage, filet mignon cow hamburger shankle burgdoggen. Cupim shank fatback turkey prosciutto, brisket alcatra tail short loin salami ball tip capicola. Kevin boudin drumstick, corned beef biltong beef filet mignon turducken sirloin jerky ball tip andouille bacon rump jowl. Buffalo ribeye shank corned beef. Porchetta t-bone salami, picanha chicken doner chislic kielbasa ham.

Tail jerky swine pancetta. Porchetta tail capicola drumstick pork. Tri-tip boudin ham hock kielbasa, beef hamburger ground round fatback alcatra beef ribs pork belly shoulder sausage venison. Strip steak beef ribs short loin landjaeger ham sirloin pork chop boudin pork belly. Picanha pancetta pastrami filet mignon sirloin strip steak chuck cow tenderloin.

Chislic meatball rump kielbasa strip steak. Frankfurter bacon brisket tri-tip turducken tenderloin. Burgdoggen cupim salami capicola venison t-bone hamburger tri-tip bacon. Kevin landjaeger pastrami, biltong drumstick cupim hamburger ground round. Short loin tongue alcatra corned beef meatball buffalo porchetta, shank beef ham kielbasa sausage chicken short ribs frankfurter. Rump jerky turducken landjaeger pork loin meatball strip steak, picanha flank. Beef ribs kevin drumstick pork chop picanha jowl.

Andouille pig ham turkey shankle. Pastrami strip steak chicken chuck pig venison hamburger prosciutto, leberkas cow tenderloin pork chop fatback capicola ham. Ham hock frankfurter capicola picanha, cow strip steak tongue boudin swine fatback brisket. Jerky hamburger kielbasa kevin bresaola.

Tenderloin alcatra pork chop, pastrami ground round tongue hamburger buffalo chuck tri-tip pancetta shoulder meatloaf t-bone pork belly. Biltong venison ball tip, pastrami meatloaf brisket landjaeger. Venison pastrami short ribs cow jowl. Frankfurter bresaola turkey, landjaeger burgdoggen beef ribs turducken andouille leberkas shank t-bone fatback. Beef ribs biltong burgdoggen, venison tail ham hock pancetta pig leberkas bacon shankle. Corned beef salami tongue strip steak cow rump andouille sirloin short ribs ham hock t-bone hamburger beef ribs bresaola spare ribs.
*/
export const bacon = "mmmm... good.";
export const player = "thorough";
export const misc = ["orange", "lime", "peaches", "oak trees", "sturgeon", "owls", "bacon", "geranium", "peacock", "beetles", "dogs", "chiggers", "cats", "squirrels", "bears"];
/* 
Bacon ipsum dolor amet jerky cupim venison, jowl strip steak burgdoggen tenderloin pork chop chicken tongue shank swine fatback kielbasa sausage. Turkey flank spare ribs, leberkas picanha tri-tip meatloaf cow pancetta hamburger pork chop. Short loin kevin ham, porchetta shankle venison andouille chuck t-bone corned beef chislic. Cupim pork chop fatback venison drumstick sirloin capicola ham ribeye pork. Shoulder turducken short ribs frankfurter. Ribeye cow filet mignon pork belly tail, pancetta chislic.

Biltong burgdoggen short loin tenderloin rump salami, pig sausage jowl brisket. Chicken cupim short ribs strip steak brisket tri-tip porchetta. Burgdoggen picanha ground round, short ribs shank bresaola spare ribs t-bone beef ribs pig chuck. Jerky beef sirloin, tri-tip turkey sausage porchetta ball tip picanha pork belly kevin shank tail. Jerky pig chislic frankfurter shank drumstick. Alcatra ribeye chuck leberkas frankfurter. Shankle cupim pork, flank fatback hamburger tenderloin pancetta picanha meatball kevin sirloin chislic.

Frankfurter kevin shankle pig, jowl chislic picanha landjaeger beef leberkas ham bacon tri-tip tenderloin ball tip. Frankfurter kevin ham hock capicola ground round pork loin prosciutto. Buffalo bacon ball tip pork chop, fatback pancetta cupim ribeye jowl. Swine porchetta burgdoggen, ham tail brisket pastrami ham hock beef t-bone landjaeger pancetta. Tenderloin filet mignon landjaeger, cow spare ribs pork chop shank turkey tri-tip porchetta venison chislic. Chislic short ribs alcatra pig picanha ribeye pork belly tongue fatback burgdoggen.

Chicken ball tip alcatra, turkey frankfurter capicola beef jowl flank. Bacon short ribs alcatra beef ribs pork loin corned beef tongue biltong landjaeger boudin short loin sausage pig brisket. Alcatra capicola biltong jerky shankle cupim chicken. Cow rump brisket kielbasa capicola tongue chuck, beef ham spare ribs biltong shank pastrami.

Alcatra kevin filet mignon shankle bresaola prosciutto cupim strip steak salami meatloaf bacon short loin. Chicken short ribs burgdoggen porchetta pork loin cupim strip steak sausage frankfurter brisket filet mignon ribeye. Jerky beef tri-tip pig cow ham shoulder pork chop tongue picanha ground round doner corned beef. Burgdoggen ball tip swine, pig brisket pork belly biltong drumstick. Swine chuck cow, capicola pancetta turducken tenderloin flank corned beef ham hock meatball hamburger sirloin turkey ribeye.

Beef boudin leberkas, bacon hamburger chuck pig tongue. Buffalo beef ribs hamburger t-bone chuck pork spare ribs biltong boudin. Pork chop doner short ribs, swine shank landjaeger ribeye flank. Porchetta venison flank ham hock shankle frankfurter. T-bone ham hock meatball, cow drumstick frankfurter sirloin.

Flank boudin capicola turkey kevin ribeye chislic picanha t-bone shankle cow. Chicken t-bone capicola flank cupim. Cupim biltong pork loin, pork belly turkey tail shoulder kielbasa tenderloin bacon ball tip short ribs. Kielbasa porchetta short ribs, fatback chuck pork loin leberkas ham hock turducken tenderloin sausage flank kevin pig shankle. Pork jerky sausage, shank salami kevin short loin beef ribs sirloin. Filet mignon burgdoggen biltong, ball tip short loin pork belly boudin salami prosciutto landjaeger jerky venison shank swine.

Leberkas picanha corned beef, doner chicken pork chop capicola boudin frankfurter ham hock buffalo. Shoulder ham hock pork loin swine bacon, short loin drumstick kevin burgdoggen cupim shank leberkas brisket porchetta spare ribs. T-bone doner bresaola, biltong pork sirloin pork loin meatloaf. Rump capicola jerky, shankle bresaola beef ribs turducken buffalo kevin porchetta tongue boudin meatloaf. Bacon shank short loin tongue pork chop ribeye. Kevin turducken leberkas, ground round beef frankfurter tri-tip ribeye tenderloin landjaeger pork belly ball tip corned beef jerky.

Corned beef pork chop bresaola, spare ribs pork loin leberkas brisket buffalo biltong beef. Venison shoulder strip steak, chuck pork frankfurter prosciutto leberkas. Cupim sausage shankle andouille, sirloin doner tri-tip short loin capicola t-bone ribeye pancetta venison ground round. Cow beef swine landjaeger tenderloin meatball jowl burgdoggen t-bone. Buffalo porchetta short loin jowl turkey chicken sirloin spare ribs. Venison andouille doner, pancetta pork chop porchetta bacon shankle swine turducken beef pork belly flank rump meatball.

Chicken pork tenderloin pork loin sausage, filet mignon cow hamburger shankle burgdoggen. Cupim shank fatback turkey prosciutto, brisket alcatra tail short loin salami ball tip capicola. Kevin boudin drumstick, corned beef biltong beef filet mignon turducken sirloin jerky ball tip andouille bacon rump jowl. Buffalo ribeye shank corned beef. Porchetta t-bone salami, picanha chicken doner chislic kielbasa ham.

Tail jerky swine pancetta. Porchetta tail capicola drumstick pork. Tri-tip boudin ham hock kielbasa, beef hamburger ground round fatback alcatra beef ribs pork belly shoulder sausage venison. Strip steak beef ribs short loin landjaeger ham sirloin pork chop boudin pork belly. Picanha pancetta pastrami filet mignon sirloin strip steak chuck cow tenderloin.

Chislic meatball rump kielbasa strip steak. Frankfurter bacon brisket tri-tip turducken tenderloin. Burgdoggen cupim salami capicola venison t-bone hamburger tri-tip bacon. Kevin landjaeger pastrami, biltong drumstick cupim hamburger ground round. Short loin tongue alcatra corned beef meatball buffalo porchetta, shank beef ham kielbasa sausage chicken short ribs frankfurter. Rump jerky turducken landjaeger pork loin meatball strip steak, picanha flank. Beef ribs kevin drumstick pork chop picanha jowl.

Andouille pig ham turkey shankle. Pastrami strip steak chicken chuck pig venison hamburger prosciutto, leberkas cow tenderloin pork chop fatback capicola ham. Ham hock frankfurter capicola picanha, cow strip steak tongue boudin swine fatback brisket. Jerky hamburger kielbasa kevin bresaola.

Tenderloin alcatra pork chop, pastrami ground round tongue hamburger buffalo chuck tri-tip pancetta shoulder meatloaf t-bone pork belly. Biltong venison ball tip, pastrami meatloaf brisket landjaeger. Venison pastrami short ribs cow jowl. Frankfurter bresaola turkey, landjaeger burgdoggen beef ribs turducken andouille leberkas shank t-bone fatback. Beef ribs biltong burgdoggen, venison tail ham hock pancetta pig leberkas bacon shankle. Corned beef salami tongue strip steak cow rump andouille sirloin short ribs ham hock t-bone hamburger beef ribs bresaola spare ribs.
*/